TERM=screen
PIP_PYTHON_PATH=/usr/bin/python3
LC_ALL=C.UTF-8
USER=root
LS_COLORS=
VIRTUAL_ENV=/root/.local/share/virtualenvs/football-4s91idYk
PATH=/root/.local/share/virtualenvs/football-4s91idYk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PWD=/root/football
EDITOR=vim
LANG=C.UTF-8
HOME=/root
SHLVL=1
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
LESSOPEN=| /usr/bin/lesspipe %s
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/env
